name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  check:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        make lint.all

    - name: Install krew
      uses: arhat-dev/actions-setup-krew@master

    - name: Check krew installed
      shell: bash
      run: |-
        if ! command -v krew ; then
          echo "krew NOT INSTALLED to PATH!"
          exit 1
        fi

        krew version
        kubectl-krew version

